/*
AQUI CREO ESQUEMA PARA EL GUARADADO EN BASE DE DATO 
EN ESTE CASO, VOY A CONTAR CON UN MODELO CITA, 
EL CUAL PUEDE DESPRENDER O PUEDE GUARDAR UN OBJETO CLIENTE
CLIENTE TENDRA: NOMBRE, CELULAR

CITA TENDRA: DIA DE LA FECHA,OBJETO CARRO, OBJETO PERSONA, 


A SU VEZ AL TRABAJAR CON CARROS DEBERIA 
MANEJAR UNA CLASE AUTOS, SOLO PARA CONOCER EL TIPO, SI ES UNA CAMIONETA, AUTO, ETC.


*/